---
apiVersion: v1
kind: Pod
metadata:
  name: mypodenv
spec:
  containers:
  - name: mypodenv
    image: alpine:3.6
    imagePullPolicy: IfNotPresent
    command:
    - sleep
    - 1d
    env:
      - name: SECRET_KEY1
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: key1
      - name: SECRET_KEY2
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: key2
---
#[dinesh@master1 ~]$ k exec -it mypodenv -- env | grep SEC
#SECRET_KEY1=supersecret
#SECRET_KEY2=topsecret

# Note: This env be accessed via docker inspect
#
# [root@worker1 ~]# docker inspect 99e326105e31 | grep SEC
# "SECRET_KEY1=supersecret",
# "SECRET_KEY2=topsecret",
#
