apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  destination:
    name: ''
    namespace: nginx
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd/nginx/chart
    repoURL: 'git@github.com:dramasamy/training.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
